#!/bin/bash
# Forked  respin respun forked stolen and modified by DasGeek
# Tested w/ Elementary OS Loki & Ubuntu 17 and 18.04 LTS BETA
# Forked and spooned from some forum post I can no longer find in a galaxy of the internet
# Version 1.2

if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./installscript"
   	exit 1
else
	#Update and Upgrade
	echo "Updating and Upgrading"
	apt-get update && sudo apt-get upgrade -y

	sudo apt-get install dialog
	cmd=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
	options=($ "Install Flatpak Repository" off
			 $# "Install Snaps Repository" on
			 1 "rxvt-unicode" on    # any option can be set to default to "on"
	     2 "Terminator" off
	     3 "Simplenote" on
	     4 "vim" on
	     5 "Filezilla" on
	     6 "" off
	     7 "subnetcalc" on
	     8 "dia" on
	     9 "Teamviewer" on
	     10 "gdebi" on
	     11 "nmap" on
	     12 "screenfetch" off
	     13 "Vivaldi" on
	     14 "tomboy Notizen" off
	     15 "GIMP" off
	     16 "Atom" on
	     17 "Putty" on
	     18 "Steam (Valve)" off
			 19 "Docky" off
			 20 "Hexchat" off
			 21 "Discord (Snap)" off
			 22 "Etcher" off
			 23 "" off
			 24 "" off
			 25 "" off
			 26 "" off
			 27 "" off
			 28 "" off
			 29 "" off
			 30 "" off
			 31 "" off
			 32 "" off
			 33 "" off
			 34 "" off
			 35 "" off
			 36 "oh my zsh" on)
		choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
		clear
		for choice in $choices
		do
		    case $choice in
	        $)
				#Install Flatpak Repository
				echo "Installing Flatpak Repository"
				sudo apt install flatpak
				;;

			$#)
				#Install Snap Repository
				echo "Installing Snap Repository"
				sudo apt install snapd
				;;


	    1) #rxvt-unicode
      echo "Installing rxvt-unicode"
      sudo apt-get install rxvt-unicode -y
      ;;
			2) #Terminator
      echo "Installing Skynet/Terminator"
      apt install terminator -y
      ;;
  		3) #Simplenote
  		echo "Installing Simplenote"
  		wget https://github.com/Automattic/simplenote-electron/releases/download/v1.1.3/Simplenote-linux-1.1.3.deb
  		cd ~/Downloads
  		sudo dpkg -i Simplenote-linux-1.1.3.deb
  		rm -rf Simplenote-linux-1.1.3.deb
  		;;
			4) #VIM
      sudo apt-get install vim -y
      ;;
			5) #Filezilla
			echo "Filezilla not related to Godzilla"
			apt install filezilla -y
			;;
			6)

			7) #subnetcalc
      sudo apt-get install subnetcalc -y
      ;;
			8) #DIA
      sudo apt-get install dia -y
      ;;
			9) #Teamviewer
      sudo apt-get purge teamviewer -y
      sudo apt-get purge teamviewer:i386 -y
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install libasound2:i386 libfontconfig1:i386 libfreetype6:i386 libjpeg62:i386 libpng12-0:i386 libsm6:i386 libxrandr2:i386 libxrender1:i386 libxtst6:i386 libxinerama1:i386 libqt5qml-graphicaleffects -y
      wget --continue 'https://download.teamviewer.com/download/linux/teamviewer_amd64.deb'
      sudo dpkg -i teamviewer_*amd64.deb
      sudo apt-get install -f -y
      rm -rf teamviewer_*amd64.deb
      ;;
			10) #gdebi
      sudo apt-get install gdebi -y
      ;;
			11) #nmap
      sudo apt-get install nmap -y
      ;;
			12) #screenfetch
      sudo apt-get install screenfetch -y
      ;;
			13) #Vivaldi
			echo "Installing Vivaldi"
			cd ~/Downloads
			wget https://downloads.vivaldi.com/stable/vivaldi-stable_1.14.1077.55-1_amd64.deb
			dpkg -i vivaldi-stable_1.14.1077.55-1_amd64.deb
			apt-get install -f -y
			rm -rf vivaldi-stable_1.14.1077.55-1_amd64.deb
			;;
			14) #tomboy
      sudo apt-get install tomboy -y
      ;;
			15) #GIMP
			echo "Installing GIMP"
			apt install gimp -y
			;;
			16) #Atom
      echo "Installing Atom"
      cd ~/Downloads
      wget -O atom-amd64.deb https://atom.io/download/deb
      dpkg -i atom-amd64.deb
      apt-get install -f -y
      rm -rf atom-amd64.deb
      apm install atom-html-preview
      ;;
			17)  #Putty
			echo "Putty"
			apt install putty -y
			;;
			18) #Steam
      echo "Installing Steam"
      apt install steam -y
      ;;
			19) #Docky
			echo "Installing Docky"
			apt install docky -y
			;;
			20) #Hexchat
			echo "Installing Hexchat"
			apt install hexchat -y
			;;
			21)	#Discord
      sudo apt install snapd
      sudo snap install discord
      ;;
			22)	#Etcher ISO Creator
			echo "Installing Etcher"
			cd ~/Downloads
			wget -O etcher.zip https://github.com/resin-io/etcher/releases/download/v1.3.1/etcher-1.3.1-linux-x86_64.zip
			sudo apt install unzip -y
			unzip etcher*.zip
			chmod +x ~/Downloads/etcher-*.AppImage
			;;
			23)
      ;;
			24)
      ;;
			25)
      ;;
			26)
      ;;
			27)
      ;;
			28)
      ;;
			29)
      ;;
			30)
      ;;
			31)
      ;;
			32)
      ;;
			33)
      ;;
			34)
      ;;
			35)
      ;;
			36) #oh-my-zsh
      sudo apt-get install curl -y
      sudo apt-get install git -y
      sudo apt-get install zsh -y
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      ;;
	    esac
	done
fi
